/*
 * C ABI for the ocrs OCR engine.
 *
 * This file is generated by cbindgen from the Rust source. Do not edit it by
 * hand. Run `just capi-header` after changing the API.
 *
 * See README.md for build, linking, and usage instructions.
 */

#ifndef OCRS_H
#define OCRS_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque handle to an OCR engine. Create with [`ocrs_engine_new`] or
// [`ocrs_engine_new_from_memory`] and release with [`ocrs_engine_free`].
typedef struct OcrsEngine OcrsEngine;

// A recognized line of text together with the axis-aligned bounding box of its
// characters in the input image (in pixels).
typedef struct OcrsTextLine {
  // NUL-terminated UTF-8 text of the line. Owned by the parent [`OcrsTextLines`].
  char *text;
  float left;
  float top;
  float right;
  float bottom;
} OcrsTextLine;

// An array of recognized text lines. Release with [`ocrs_text_lines_free`].
typedef struct OcrsTextLines {
  struct OcrsTextLine *lines;
  size_t len;
} OcrsTextLines;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Return the calling thread's most recent error message.
//
// The returned pointer is owned by the library and remains valid until the
// next fallible call on the same thread. Returns NULL if there is no error.
const char *ocrs_last_error(void);

// Create an engine, loading the detection and recognition models from files.
//
// `detection_model_path` and `recognition_model_path` are NUL-terminated paths
// to `.onnx` model files. Either may be NULL to omit that model, though
// detection is required for [`ocrs_engine_get_text`] and recognition is
// required for any text output.
//
// Returns NULL on failure. See [`ocrs_last_error`].
//
// # Safety
//
// Each non-NULL path argument must point to a NUL-terminated C string.
struct OcrsEngine *ocrs_engine_new(const char *detection_model_path,
                                   const char *recognition_model_path);

// Create an engine from models held in memory.
//
// Each model is read from a buffer of `*_len` bytes. A NULL pointer (with any
// length) omits that model. The buffers are only read during this call and may
// be freed by the caller afterwards.
//
// Returns NULL on failure. See [`ocrs_last_error`].
//
// # Safety
//
// Each non-NULL model pointer must point to at least `*_len` readable bytes.
struct OcrsEngine *ocrs_engine_new_from_memory(const uint8_t *detection_model,
                                               size_t detection_model_len,
                                               const uint8_t *recognition_model,
                                               size_t recognition_model_len);

// Free an engine created by `ocrs_engine_new*`. Passing NULL is a no-op.
//
// # Safety
//
// `engine` must be NULL or a pointer returned by `ocrs_engine_new*` that has
// not already been freed.
void ocrs_engine_free(struct OcrsEngine *engine);

// Detect and recognize all text in an image and return it as a single
// NUL-terminated UTF-8 string, with lines separated by `\n`.
//
// `image_data` points to `width * height * channels` bytes in HWC order.
// The engine must have both a detection and a recognition model.
//
// Returns NULL on failure. See [`ocrs_last_error`]. Free the result with
// [`ocrs_string_free`].
//
// # Safety
//
// `engine` must be a valid engine pointer and `image_data` must point to at
// least `width * height * channels` readable bytes.
char *ocrs_engine_get_text(const struct OcrsEngine *engine,
                           const uint8_t *image_data,
                           uint32_t width,
                           uint32_t height,
                           uint32_t channels);

// Detect and recognize text, returning per-line text and bounding boxes.
//
// `image_data` points to `width * height * channels` bytes in HWC order. The
// engine must have both a detection and a recognition model. Lines with no
// recognized characters are omitted.
//
// Returns NULL on failure. See [`ocrs_last_error`]. Free the result with
// [`ocrs_text_lines_free`].
//
// # Safety
//
// `engine` must be a valid engine pointer and `image_data` must point to at
// least `width * height * channels` readable bytes.
struct OcrsTextLines *ocrs_engine_get_text_lines(const struct OcrsEngine *engine,
                                                 const uint8_t *image_data,
                                                 uint32_t width,
                                                 uint32_t height,
                                                 uint32_t channels);

// Free a string returned by [`ocrs_engine_get_text`]. Passing NULL is a no-op.
//
// # Safety
//
// `text` must be NULL or a pointer returned by [`ocrs_engine_get_text`] that
// has not already been freed.
void ocrs_string_free(char *text);

// Free a result returned by [`ocrs_engine_get_text_lines`], including every
// line's text. Passing NULL is a no-op.
//
// # Safety
//
// `lines` must be NULL or a pointer returned by [`ocrs_engine_get_text_lines`]
// that has not already been freed.
void ocrs_text_lines_free(struct OcrsTextLines *lines);

// Return the ocrs version as a static NUL-terminated string.
const char *ocrs_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OCRS_H */
