[workspace]
resolver = "2"
members = [
  "ocrs",
  "ocrs-cli",
]

[workspace.dependencies]
rten = { version = "0.23.0", default-features = false, features = ["rten_format"] }
rten-imageproc = { version = "0.23.0" }
rten-tensor = { version = "0.23.0" }
