//! Verifies that the committed C header (`include/ocrs.h`) matches the Rust API.
//!
//! The header is generated by cbindgen.
//! This checks if the two drift (like after changing an `extern "C"` signature
//! or a `#[repr(C)]` type without regenerating).
//!
//! To regenerate after an intentional API change:
//!
//! ```sh
//! make capi-header # or: OCRS_UPDATE_HEADER=1 cargo test -p ocrs-capi --test header
//! ```

use std::path::PathBuf;

fn header_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("include/ocrs.h")
}

fn generate() -> String {
    let crate_dir = env!("CARGO_MANIFEST_DIR");
    let config = cbindgen::Config::from_root_or_default(crate_dir);
    let bindings = cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .generate()
        .expect("cbindgen failed to generate the header");

    let mut out = Vec::new();
    bindings.write(&mut out);
    String::from_utf8(out).expect("generated header is not UTF-8")
}

#[test]
fn header_is_up_to_date() {
    let generated = generate();
    let path = header_path();

    if std::env::var_os("OCRS_UPDATE_HEADER").is_some() {
        std::fs::write(&path, &generated).expect("failed to write header");
        eprintln!("wrote {}", path.display());
        return;
    }

    let committed = std::fs::read_to_string(&path).expect("failed to read include/ocrs.h");
    assert_eq!(
        normalize(&generated),
        normalize(&committed),
        "include/ocrs.h is out of date with the Rust API; regenerate with `make capi-header`",
    );
}

/// Ignore trailing-whitespace and line-ending differences so the test passes
/// regardless of how the header was checked out (e.g. CRLF on Windows).
fn normalize(text: &str) -> String {
    text.replace("\r\n", "\n")
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n")
}
